### ISSUE TITLE
SONAR.Heuristic.170

### ISSUE THREAD

**Issue by rick7777** [sparklecoin/sparklecoin#1]
Trojan virus detected by antivirus will not allow installation

**Comment by sparklecoin** [comment]
please provide more information, what is the url of file with detected virus and what antivirus software do you use?

sometimes cryptocurrency wallets get falsely flagged as trojans, we use virustotal to check most of the antivirus engines. for example here's the output of check of our windows wallet:

https://www.virustotal.com/#/url/850c1fa3e20f6d5450e36431ee913a0769d88489b3830c2a01d26f8cb39dea78/detection
