### ISSUE TITLE
Checkpoint Warning

### ISSUE THREAD

**Issue by MjGenius** [sparklecoin/sparklecoin#2]
There is a message at the bottom of my Sparkle wallet "WARNING: CHECKPOINT IS TOO OLD, WAIT FOR BLOCK CHAIN TO DOWNLOAD OR NOTIFY DEVELOPER OF THIS ISSUE" As far as I can tell the green check mark says the wallet is UP TO DATE. what is the solution? thanks.

**Comment by sparklecoin** [comment]
thank you for reporting, checkpoint node was stuck, should be fixed now!
