### ISSUE TITLE
How do I add sparklecoin to my wallet?

### ISSUE THREAD

**Issue by hutchanis** [sparklecoin/sparklecoin#4]
I bought in to sparklecoin but when i did i didn't have the wallet set up. So, How do I add the coin(s) to my wallet? BTW, I am new to this.

**Comment by oriburi** [comment]
you should log in to laptop computer and download the files from github.
That is only way for now. It doesnt support any of mobile devices.

**Comment by SparkleCOIN-Support** [comment]
Did you provide the wallet address to the support@sparklecoin.com team? It may be that you haven't sent your information to us, which is why you haven't received your coins yet.
