### ISSUE TITLE
OSX Version 1.1 Bad Binary

### ISSUE THREAD

**Issue by freecrm** [sparklecoin/sparklecoin#6]
The OSX Binary for the new client wallet is bad.

It's corrupt.

**Comment by Juliesta** [comment]
This is an absolute disgrace. You are supposedly professionals and you send us corrupted files. Please send us another exe program not corrupted

**Comment by hemlockboy** [comment]
Class action, these guys are phonies!

**Comment by SparkleCOIN-Support** [comment]
Has everyone tried re-downloading the software and installing (not just trying to re-install using the previous download)? The MacOS v1.1.0.0 wallet has been working for multiple users since Thursday, Jan 11th. If it is still not working, please submit an email to support@sparklecoin.com.

**Comment by stephenfortner** [comment]
I just tried the re-downloading per the instructions above, and though I was having the bad binary problem before, this corrected it. I can now see my SPRK just fine.

**Comment by freecrm** [comment]
This is now fixed, thanks.
