### ISSUE TITLE
The new wallet not working in windows 10

### ISSUE THREAD

**Issue by sqlau** [sparklecoin/sparklecoin#8]
I downloaded the new wallet exe, and uninstall the old one. 
BUT I run the new wallet exe installation file, NOTHING HAPPEN!!!!!!!!!!!!

**Comment by JacKaL424** [comment]
Here is what I did:

1) Exited current sparkle coin app
2) I downloaded Sparklecoin-1.1.0.0-win.exe
3) Installed it
4) Opened it

All my coins were there plus some new minted ones.

I had no issues.

**Comment by SparkleCOIN-Support** [comment]
Sqlau, 

You will not notice a visual difference between the 2. One way to see the version you are running, is to open your wallet, click "Help" at the top left, then click "About Sparklecoin". You should see v1.1.0.0. 

If you are not sure about the update process, please see the link below:
https://sparklecoin.com/blogs/news/wallet-update-v1-1-0-0-walkthrough

**Comment by sqlau** [comment]
Thanks relay.

It seems the Windows 10 ‘s problem. I upgrade to the newest version of Win10 , and Fix.

The wallet version 1.1.0.0 is working.



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: JacKaL424 <notifications@github.com>
发送时间: Tuesday, January 16, 2018 5:40:22 AM
收件人: sparklecoin/sparklecoin
抄送: sqlau; Author
主题: Re: [sparklecoin/sparklecoin] The new wallet not working in windows 10 (#8)


Here is what I did:

  1.  Exited current sparkle coin app
  2.  I downloaded Sparklecoin-1.1.0.0-win.exe
  3.  Installed it
  4.  Opened it

All my coins were there plus some new minted ones.

I had no issues.

―
