### ISSUE TITLE
Sending from Wallet to Exchange Error

### ISSUE THREAD

**Issue by JacKaL424** [sparklecoin/sparklecoin#9]
I used a previous Sparkle Address from the exchange to send coins from Wallet.  However, I get the attached error.
![capture](https://user-images.githubusercontent.com/16445056/34963006-e800bc70-fa0b-11e7-8bd8-2429bf9ea028.JPG)?

**Comment by JacKaL424** [comment]
This might be related to my coin maturity issue.  My coins should not be maturing, they should be available.

**Comment by SparkleCOIN-Support** [comment]
JacKaL424, 

If your coins are maturing, they will not be able to be used for 500 blocks (which is roughly 3 days). Can you send a screenshot of your Overview page and Minting page to support@sparklecoin.com?

**Comment by JacKaL424** [comment]
The problem is, why are they even maturing? I have had them since Sept 2017.  They should be available.  Yes I'll send the requested items.

**Comment by SparkleCOIN-Support** [comment]
Maturing/Minting is based on the PoS (Proof of Stake) aspect of our system. Your coins have gone into a minting/maturing state and will be released to be transacted with once they finish minting.

**Comment by JacKaL424** [comment]
Ok,  Makes sense.
